# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ec3ac768da2b8aa56fefba5c8395ab2bb57e5037add42cbd34729deec0480e8d0cc74b3f489e5ae3daf40b996f5d787fb2446a7185665a390b20582213a826d

test:
  secret_key_base: 48b41cfd7517c022d44af1e916ded83b827ba4af6f88bac847f2d0cb7f575a404e38be6d0d6654073d1e3dfb68ea51554c754255c0c64fb82d81a9faefe72847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
